### ISSUE TITLE
Portal auto-updating client uninstall script is incomplete

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#12]
Clients are finding issues from time to time with the Uninstall Process. Currently if they are having issues, we direct them to a powershell script, but it would be good to review how to uninstall/reinstall especially so it can be RMM driven.
May need to review documentation?

This is related to issue from `User Voice`. https://github.com/DeskDirector/UserVoice/issues/40

**Comment by chris-ls** [comment]
The uninstall script has two pieces.
1) Uninstall the MSI
2) Uninstall the portal from any user account on the machine.

Part 2) relies on executing "Update.exe --uninstall -s" for each user, which is responsible for removing the shortcuts that it created on the desktop,startup folder & startmenu.

e.g. 
`C:\Users\Bob\AppData\Local\deskdirectorportal\Update.exe --uninstall -s`
`C:\Users\Alice\AppData\Local\deskdirectorportal\Update.exe --uninstall -s`

The problem is that Update.exe is being invoked by the user who is running the script.
Update.exe is designed to be run in the context of the user where the application lives.
i.e. Alice or Bob.
It is therefore trying to clean-up the installation just for the admin user running the script, not Alice or Bob.
This behavior is hardcoded into Update.exe and is part of auto-updating code we don't own.

The easiest way would be to modify the script to execute Part 2) in the context of each different user on the machine.

**Comment by chris-ls** [comment]
Work has commenced on this.
We should be able to provide a complete uninstall script shortly.

**Comment by chris-ls** [comment]
Script is nearing completion

**Comment by chris-ls** [comment]
Uninstallation script and instructions are available inside one of our HelpDoc's KB articles.
You can find this here:
https://help.deskdirector.com/article/fdugn6q4k7-uninstall-script-for-ddportal
