### ISSUE TITLE
[8178] Desktop Portal having trouble on open URL Link

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#4]
The challenge to open URL link in electron application is some of JavaScript code conflict with Node.js, which cause page not rendering.

One of example is URL link contain inside wufoo form been rendered as blank page.

**Comment by chris-ls** [comment]
This issue is fixed inside Desktop/v1.72.

All content which opens inside a new tab in the browser, will now open inside a new 'Modal Window' in the desktop client.

This Modal Window will be centered above the application and take focus. The user will not be able to interact with the main application while this Modal Window is displayed.
