### ISSUE TITLE
[8821] Improve Portal Quote list view

### ISSUE THREAD

**Issue by Nness** [DeskDirector/Issues#6]
* Dollar signs on price amount, plus 2 decimal places after as these are regular currency fields. (Display as currency)
* Quosal number display, scenario for this is when customer request same thing multiple times, title of quote might be same. We can use Quosal number to differentiate them.

**Comment by chris-ls** [comment]
* We can ensure there is 2 decimal places for the currency fields.
* We can display a dollar sign ($) on these fields as well. This obviously doesn't work _everywhere_ (e.g. UK). As we do not have access to the correct currency symbol, the choice is between leaving this blank (no currency symbol) or using a 'default' one (dollar). The argument for using a 'default' one, is to help suggest to the user that it is a monetary value.
* We don't have access to the Quosal number, so cannot show this. The real issue is the inability to distinguish between quotes with the same name, in the list view. The UI could be reworked slightly in order to display the QuoteDetail. The QuoteDetail could be leveraged to provide more information (e.g. the Quosal Number could be put here by the quote creator)

**Comment by chris-ls** [comment]
We do now have access to the currency information for each Quote.
The UI needs to be updated to use this new information.

**Comment by chris-ls** [comment]
Currency symbol has been added to currency fields when displaying quote line-items.

**Comment by chris-ls** [comment]
Quote line items will now display with their corresponding currency symbol.
This will be deployed with:
Portal Web/v2.18.11 - Released 23/07/18
Portal Desktop/v1.74.0 - Released 24/07/18
