### ISSUE TITLE
[10461, 10814, 10821, 11030, 11373] Emails not being sent when adding time entries

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#8]
We're not why exactly this happens for some people and not others, we've not been able to confirm with ConnectWise.

We do have some idea on what we need to do to fix, but we want to do more testing to confirm.

**Comment by PreciseNZ** [comment]
Does CW require a change in status to fire the workflow?

**Comment by Aycorn** [comment]
Additionally raised on ticket: Service Ticket #10821 - DD-Tech Email contact on update

**Comment by FluidNets-DamianS** [comment]
So oddly enough I just updated a ticket through DD-Tech-Dev and the notification was sent.  However we do not use "Workflows" to trigger these emails.  I am trying to exclusively use DD Tech for updates so if there is something you want me to check I am happy to do so.

**Comment by Andrew-Lahikainen** [comment]
Strange, tech-dev hasn't had any changes relating to this. We've implemented the api for allowing contact/resource notifications from a time entry. Tech just needs to implement these flags.

I hope to get onto working on this shortly.

**Comment by Aycorn** [comment]
Additionally raised on ticket: Service Ticket #10821 - DD-Tech Email contact on update

**Comment by Aycorn** [comment]
Additionally raised on ticket: Service Ticket #11030 - Email notifications aren't sent to techs when client updates DD

**Comment by iqinit** [comment]
So it looks like the problem might be something as simple as setting the email flags for public updates rather than internal updates when you create the Time Entries: 
emailResourceFlag(Boolean)
emailContactFlag(Boolean)
emailCcFlag(Boolean)
emailCc(String)
https://developer.connectwise.com/manage/rest?a=Time&e=TimeEntries&o=CREATE

I have just tested with debugging enabled at the Connectwise end and can see those fields are not being passed in the time entry POST request. Bug might be you are not sending those values at all, or the bug might be in your logic check to see if the update is public or internal if you are already sending them. Here is what is being received at our end:

{\"chargeToId\":XXXXX,\"chargeToType\":\"ServiceTicket\",\"member\":{\"id\":XXX},\"workType\":{\"id\":3},\"timeStart\":\"2018-08-08T07:37:34Z\",\"timeEnd\":\"2018-08-08T07:38:34Z\",\"billableOption\":\"Billable\",\"notes\":\"Another Public Note\",\"addToDetailDescriptionFlag\":true,\"addToInternalAnalysisFlag\":false,\"addToResolutionFlag\":false,\"hoursBilled\":0.0}",

**Comment by Nness** [comment]
Thanks for pass through your findings. We do aware of those flags. The reason we didn't pass those flag is difference between RESTful API and SOAP API.

* SOAP API: If we pass flag as null, it will use default setting. which is according to board's setting
* RESTful API: It doesn't respect board's default setting.

DeskDirector is build for large group of customers. We cannot pass that flag over without knowing customer's intention.

The result is get board configuration, so that TECH respect that, apply those default setting when creating ticket.

From [Board entity](https://developer.connectwise.com/manage/rest?a=Service&e=Boards&o=GET) you can find 3 flags.

* SendToResource
* SendToContact
* SendToCc

**Comment by Nness** [comment]
Currently our developer is working through some of refactor and issues. We will get on to this soon and will keep everyone updated.

**Comment by iqinit** [comment]
So then handle it the same way Connectwise does and give us three checkboxes at the bottom we can tick or untick on a per reply basis. You are now forcing us to use DD-Tech if we want to use chat which is the whole reason we got Desk Director and yet the most basic of functionality doesn't work! Can you also look into why none of my requests to suspend our account or get a refund have been answered! We haven't been able to roll out Desk Director to a single customer yet because of this!

**Comment by Nness** [comment]
Hi @lwhitelock . Could you message to support@deskdirector.com? At current stage, chat v4 and TECH has not yet been released and not even announced public beta. For refund on what you have purchase, our customer success manager should be able to give you an update next Monday. Inside email just tell them you want to talk to customer success manager, they will pass your message through.

Sorry for your bad experience. People who answering in here are developers and supports. Also we cannot check who you are on this platform, so we cannot associate you with the actual case.

**Comment by Aycorn** [comment]
Additionally raised on ticket: Service Ticket #11373 - Bizarre behavior when Desk Director Posts customer updates to ConnectWise Tickets

**Comment by Andrew-Lahikainen** [comment]
@Aycorn I don't think that ticket is related. That request seems to be regarding Portal, not Tech. Could you please check again and let me know if I've got something wrong?

**Comment by Andrew-Lahikainen** [comment]
This has been implemented and deployed (TECH 1.6.2). Please test it out and let me know if there are any bugs. Will close this issue for now.

**Comment by FluidNets-DamianS** [comment]
@Andrew-Lahikainen So I have some issues with this already.  The check boxes are unchecked by default.  What if someone has explicitly set some alerting options in CW?   For me I use MS Flow to automatically add CC's / POC to tickets.  In addition I don't want Tech's thinking if they should tick the box or not.  If the notification boxes are checked in CW then TECH should have the boxes checked too.

**Comment by Andrew-Lahikainen** [comment]
Ok, will look into it. Little point in actually having the checkboxes at all in your case but i just know others will need them.

**Comment by FluidNets-DamianS** [comment]
CW give me check boxes that techs can un-check when necessary.  Not for hiding the update but if not wanting to create more email noise.  I like the boxes they just need to be in sync.

**Comment by Andrew-Lahikainen** [comment]
I think my gripe with these checkboxes is that they feel unnecessary. It makes sense to me that if a note is public, it sends an email to all parties involved. However, ConnectWise has 3 flags to determine who to notifiy, and these get sent regardless of whether the note is internal or not.

At some point I think we (DeskDirector) need to take a stance on how level 1 helpdesk technicians work tickets and enforce that. For instance, internal notes will only notify resources. Public notes will notify Ccs, the contact, and resources. This is much simpler and makes sense for a helpdesk team. I understand perhaps not sending emails for projects or "internal" boards, but that's not part of TECH's scope. If we continue to support all of ConnectWise's and Autotask's features we're going to end up being even more bloated than they are.

**Comment by Nness** [comment]
To be clear.

## TECH
* Internal Note: Send to resources
* Resolution or Detail description: Send to contacts and CC.

## Portal
Always send to resources and CC. Contacts if given contact is not the owner of ticket.

**Comment by FluidNets-DamianS** [comment]
I like the idea, but we will need to figure out how to make the same logic apply for lever 2+ techs that work in CW.  The main reason is training.  I do not like the CW internal note and we specifically do not use it at all at the moment.
As far as the comment by  @Nness  for tech:

- Internal Note: Send to resources, but not the resource who submitted the note
- Resolution or Detail description Send to contacts, CC and resources, but not the resource who submitted the note

This is something I hate about CW.  I actually built workflow rules in Exchange to dispose of emails that originate from "Updating Resource" and being sent to "Updating Resource".  However, if another resource or tech updates a ticket that I am a resource on - then I need to know about it since it is my ticket.

When I used to be on Autotask we did use the internal notes section.  However all we did was automatically append "##!##" at the bottom of the email to indicate there was an internal note to look at.

I am hoping that we will start internal note in the future to reference technical "nerd" stuff about the resolution and leave the discussion/resolution as clean human talk directed for the end-user.

**Comment by Nness** [comment]
When I type out those rules there, it is struggling me as well. I would love to achieve what you have post there. There is no point to send to people who wrote the note.

As the worst case scenario, by using CW to notify. All we can achieve is either send to all resources assigned to ticket. Same goes to CC.

We could possible include logic like, if only one member assigned to the ticket, is that member who wrote this internal note? If yes, don't send to anyone. If no send to all resources who assigned to the ticket.

For normal note, logic will be, are there other member assign to the ticket? If yes, send to all resources.  Else send to CC and contact only.

By sending email, I mean turn those flag on. CW API expose 3 flags. Send to contact, send to resources, send to CC.

**Comment by Andrew-Lahikainen** [comment]
@FluidNets-DamianS I deployed a build a few hours ago that should now select your default notification options on those checkboxes. Hopefully that can satisfy the majority of people until we can really take a good look at entering time entries/notes.

**Comment by FluidNets-DamianS** [comment]
That works!

**Comment by FluidNets-DamianS** [comment]
@Nness The other problem is that I find often that CC will also include other Techs.  I may add myself as a CC to a ticket that another tech is working on.  I dont want to be added as a "Resource" because I am not working on the issue, but I want to be CC'd.  If this is the case then I would not receive alerts for internal notes.  I know CW recently added the "Follow" function for tickets although I do not really see where anything happens because of it unless you create workflow emails which are almost useless since they cannot include [timeentrynotes].

**Comment by FluidNets-DamianS** [comment]
@Nness but we could use the "Follow" as a CC reference for internal techs/employees.

**Comment by Nness** [comment]
I just checked whether there are follow flag on the model. I'm afraid that not only follow not in there. But ticket note doesn't appear to have ability to perform `cc` or send email. That means ticket note's behaviour is guarded by CW. While time entry is not.

There are 3 flags inside time entry, `emailCcFlag`, `emailResourceFlag`, `emailContactFlag`. I couldn't see anything related to follow yet.

```
// create note payload
ServiceNote {
	id(Integer)
	ticketId(Integer)
	text(String)
	detailDescriptionFlag(Boolean)
	internalAnalysisFlag(Boolean)
	resolutionFlag(Boolean)
	member(MemberReference)
	contact(ContactReference)
	customerUpdatedFlag(Boolean)
	processNotifications(Boolean)
	dateCreated (String)
	createdBy (String)
	internalFlag (Boolean)
	externalFlag (Boolean)
	_info (Metadata)
}
```

```
// create time entry payload
TimeEntry {
	id(Integer)
	* company(CompanyReference)
	* chargeToId(Integer)
	* chargeToType(Enum)
	member(MemberReference)
	locationId(Integer)
	businessUnitId(Integer)
	workType(WorkTypeReference)
	workRole(WorkRoleReference)
	agreement(AgreementReference)
	* timeStart(String)
	timeEnd(String)
	hoursDeduct(Number)
	actualHours(Number)
	billableOption(Enum)
	notes(String)
	internalNotes(String)
	addToDetailDescriptionFlag(Boolean)
	addToInternalAnalysisFlag(Boolean)
	addToResolutionFlag(Boolean)
	emailResourceFlag(Boolean)
	emailContactFlag(Boolean)
	emailCcFlag(Boolean)
	emailCc(String)
	hoursBilled (Number)
	enteredBy (String)
	dateEntered (String)
	invoice (InvoiceReference)
	mobileGuid(Guid)
	hourlyRate(Number)
	timeSheet (TimeSheetReference)
	status (Enum)
	_info (Metadata)
	customFields(CustomFieldValue[])
}
```

**Comment by FluidNets-DamianS** [comment]
Ok. “Follow” is for like easy grouping within CW.  Bleh! https://docs.connectwise.com/ConnectWise_Documentation/020/015/020/050

What is the difference between ticket note and time entry?

**Comment by Nness** [comment]
Ticket note only apply to ticket. Time entry can be for ticket or other entities. That's why it has `chargeToId`, `chargeToType`. Of course as you already know, time entry will include ability to have time associated with it. Where note doesn't. 

Internally, the note of time entry is saved inside ticket note collection I believe. The reason is exposed by SOAP API. In SOAP API, ticket detail return 3 collection of notes, no time entry at all. But you can see time entry inside those notes collection, the ID is different.

Other than that, it's just the difference you can see from interface. I do notice ConnectWise no longer promote ticket note in their interface, at least it is hard to find. 4 years ago it was not the case, it is much easier to add note than time entry. Now the button for add note become add time entry.

From purpose point of view, note is for conversation, while time entry should be for what happened or what that engineer did to this ticket. Whether engineers been follow that purpose or not, I'm not certain. My guess is engineers are using time entry as conversation tools.

**Comment by FluidNets-DamianS** [comment]
Ok, cause this is the only way i know to create a note: 
![image](https://user-images.githubusercontent.com/10325877/44818518-403e7500-abb7-11e8-96d6-91090a07f9f8.png)

**Comment by Nness** [comment]
What you showing there is time entry. There is an interface to create note. So hard to find where that functionality is now. Probably they remove completely from current CW. so engineer cannot see that option anymore, but through API we can still do that.

**Comment by FluidNets-DamianS** [comment]
Ok, this is the only way to create a Discussion/Resolution or Internal note.  The other reason we don't really use "internal" note is that if a tech submits time it creates an invoice discrepancy as well since we dont show this on the invoice so the customer does not know what they are paying for.  Even funnier is that in addition to:
- Description
- Resolution
- Internal
There is also "Internal Time Note" which is different than "Internal" and is for further clarification to the time card approver.  I wish CW would implement hover/help so we didnt have to research all these stupid fields.

I wonder if this is where "notes" get generated from since there is no email function...
![image](https://user-images.githubusercontent.com/10325877/44847360-3baea680-ac21-11e8-869b-b228f94dcdd4.png)

**Comment by Nness** [comment]
This is definitely the UI I have used before. It is normal ticket note for ticket.

You are correct, time entry's internal note is confusing, it is internal note to the time entry not to ticket.

The other funny behaviour is, those flags are individual. What that means is if you tick discussion and internal, customer will be able to see it through portal. (CW portal). 

We do have other user voice that asking us to show note to customer when it is marked as internal and resolution, because ConnectWise did so. Of course their reasoning is in a way acceptable, they said with certain difficulty, one of CW plugin logging automatic note as internal and resolution.

This is a bit off topic from email, but our decision on those flag is different from it's original. We purely respect internal flag, if it is marked internal then it mean to be internal.

For email part, when create note, the only thing we can specify is notificationFlag, when that one is ticked, it will email customer, no matter whether it is internal or not. If it is default or not defined, then CW will decide who will email to. That's the limitation on create note.

Where create time entry, we have 3 flag to use for.

**Comment by FluidNets-DamianS** [comment]
@Nness I agree that internal should be just that "internal" and should never be seen by a customer.  In CW when you tag a customer as an admin they see everything which we never liked and again, another reason we never used.
