### ISSUE TITLE
[18509] Master admins are still able to edit the admin console after they have their master admin permission revoked

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [DeskDirector/Issues#93]
To reproduce:

* Impersonate a master admin (A)
* Impersonate another master admin (B) incognito
* Remove A's master admin permission as B
* A should still be able to navigate and edit the admin console

@Nness suspects this is due to the member cache not being updated after they are updated.

**Comment by Nness** [comment]
This issue is related to roles been cached for 15 min and not been updated after it has been altered. 

Server 18.78.1 should resolve this issue. Expected release date is 17th of June. Existing logic's security issue is not as major as it seems. Since after alter the permission, it will have 15min maximum time. Normally is fine unless that user is actively try to damage the system.

------------------
There are several special case, where master admin flag is not been respected.
* ConnectWise API license type member cannot be master admin
* ConnectWise Contractor license type member cannot be master admin.
* ConnectWise member role named as `Admin` will automatically grant master admin permission.
* During onboarding, if a given user's email has been put inside server setting to be admin, then he will always be master admin. (It is normally not the case, where new customer's initial login's user name was always same, not use email).
